### ISSUE TITLE
[Request] Hide keyboard accessory bar

### ISSUE THREAD

**Issue by tiendq** [mhweiner/CordovaiOSKeyboardPlugin#1]
Could you update this plugin to allow keyboard accessory bar to be hidden? it's a high demand feature that other plugins implemented.

Thanks,

**Comment by mhweiner** [comment]
I originally had that feature included (forked from https://github.com/don/KeyboardToolbarRemover). I removed it once I discovered that it can get your app rejected. The only known tricks involve using undocumented classes or extending the UIWebView, all of which is not allowed by Apple. See this for reference:

http://www.aerych.com/blog/2012/04/29/uiwebviews-uikeyboards-and-uitoolbars-oh-my/

**Comment by tiendq** [comment]
Oh, does KeyboardToolbarRemover use the same method with Cordova Keyboard plugin? If yes then you don't need to worry about it since lots of apps are using it, including one of mine, and I've never heard any rejection.

**Comment by mhweiner** [comment]
Interesting, that's good to know. However, there is also a bug with it; when that feature is enabled, keyboard height isn't taking that into consideration (it reports the same height), and even worse, that area won't accept touch events. If you could find a way to fix this issue, I will gladly accept pull requests and add this feature back in. I'd rather not release buggy features.

**Comment by austinjackson** [comment]
I might add that when using the keyboard toolbar remover plugin by itself without this plugin, the area beneath the (removed) toolbar does, in fact, accept touch events.  Would be great to see this functionality added, since they won't work together and this plugin is the only keyboard plugin that actually works for iOS.

**Comment by mhweiner** [comment]
I'd love to find a way to make them work together, however I do have a problem with using private classes in my apps. Also, it seems to be a bit of work to make it happen...if you want to try to do this, I can make a separate branch/repo for it. That way, people can choose if they are OK with using the private classes or not. However, I don't have the time to work on this right now. :(

**Comment by austinjackson** [comment]
Thanks for the reply.  I don't have the knowledge...
