### ISSUE TITLE
Error using plugin

### ISSUE THREAD

**Issue by jamersan** [mhweiner/CordovaiOSKeyboardPlugin#2]
I have the plugin installed on my app.   I have the following code:  

document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady(){
  Keyboard.resizeApp(true);
 console.log("Open: " + Keyboard.isOpen());
}

After the resizeApp call, I can see in the the console where it says "Keyboard will resize app.".  However, the isOpen call returns "undefined" so I see  "Open: undefined" in the console log.   

I have cordova 3.3.1-0.1.2 installed.  Any suggestions?

**Comment by mhweiner** [comment]
The issue was the until any events were fired, variables 'open' and 'keyboard_height' were both null. I corrected it so that they are false and 0 respectively. Thanks for finding the bug! :+1:
