### ISSUE TITLE
Support for Cordova 3.3?

### ISSUE THREAD

**Issue by hotzenklotz** [mhweiner/CordovaiOSKeyboardPlugin#3]
Hi,

I just tried using the plugin with Cordova 3.3.1-0.1.2 but to no avail. I don't get any of the Keyboard events and it looks like Keyboard.isOpen() doesn't seem to work either. Check out the screenshot:

![screen shot 2014-01-29 at 13 04 31](https://f.cloud.github.com/assets/1105056/2026894/0f823866-88a3-11e3-9caa-780143b7fbe6.png)

I am on OSX 10.9 and use the iOS 7 Simulator. My config.xml does not contain any KeyboardShrink etc. parameters.
Can you please confirm that the plugin still works under Cordova 3.3? Thank you very much.

**Comment by mhweiner** [comment]
I have not yet tested under Cordova 3.3. I'll test and confirm. In the meantime, make sure the plugin is properly installed using the CLI. Occasionally, I've noticed the CLI doesn't install plugins correctly, so uninstalling and reinstalling sometimes solves these kinds of issues. Also, make sure you don't have any other keyboard plugin installed, or anything else taking over the global Keyboard namespace.

**Comment by hotzenklotz** [comment]
I double checked that the global variable "Keyboard" doesn't get overwritten. Logging "Keyboard" in Safari returns an object with all the right methods.
I removed and reinstalled the plugin again via CLI but that didn't help either. The Keyboard.m and Keyboard.h files both show up in XCode and the project compiles without problems.

**Comment by mhweiner** [comment]
I'm not going to have a chance to check it out tonight, but I'll try tomorrow. If you can figure it out before I get a chance, please submit a pull request. Sorry about the issue. I'm not sure what (if anything) has changed from 3.2 to 3.3 to stop it from working...

**Comment by hotzenklotz** [comment]
I am sorry to bother you again, but have you had a chance to verify. I feel like I tried everything but to no avail. Thank you.

**Comment by roscadaniel** [comment]
I confirm that the plugin is not responding to Cordova 3.3. I have been trying to integrate it into an app around 10th of January but the methods return false every time although the global Keyboard variable is defined and this makes it even more strange than it should be.

**Comment by hotzenklotz** [comment]
@mhweiner Have you had a chance to look into this? I would really love to be able to use this plugin again. Thank you very much.

**Comment by mhweiner** [comment]
I haven't had a chance yet, I'm hoping to do this tonight. Thanks! Very curious why it would stop working.

**Comment by normanrz** [comment]
I just stepped through the code and found out that `Keyboard.setup` is never called. 
Not sure if the app code is supposed to call that or if it was called by Cordova in earlier versions.

**Comment by mhweiner** [comment]
Good catch ! Yes, it's required that you call it in the app code yourself.
I'm so sorry I forgot to add that to the documentation. +1 I'll do that now.

**Comment by normanrz** [comment]
Thanks :-)
Why does it have to be explicit? Is there no way of initializing automatically?

**Comment by mhweiner** [comment]
I probably did this for some reason (like saving resources if it wasn't necessary). I'll have to think about it and either instantiate explicitly, have an option, or update the docs accordingly. I'll close this out when I've done this.

**Comment by 23tux** [comment]
I can also reproduce some of the issues. The `Keyboard.setup()` has to be called, otherwise `.isOpen()` always returns false.

Unfortunately, the events aren't triggered, regardless if you call `setup()` or not. I'm using Cordova 3.4.0-0.1.3 and tried deinstalling and re-installing the plugin. Nothing works.

Is there a chance, to get this to work in 3.4? Or are there so many differences between the versions?

**Comment by mhweiner** [comment]
I have fixed all of these issues, thanks for your patience. Unfortunately, iOS7.1 required me to remove the resizeApp() functionality. Other people were having issues, and iOS7.1 just broke it anyway. The README has been updated, please review the changes before updating your app. Thanks! Let me know if there is anything else I can do or any questions you might have.
