### ISSUE TITLE
iOS7 status bar: View gets resized

### ISSUE THREAD

**Issue by 23tux** [mhweiner/CordovaiOSKeyboardPlugin#5]
Hi,

for iOS7, I want to display the status bar on top, and not over my content. So I changed the `viewWillAppear` method in my `MainViewController.m` to this:

```
- (void)viewWillAppear:(BOOL)animated
{
    //Lower screen 20px on ios 7
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7) {
        CGRect viewBounds = [self.view bounds];
        viewBounds.origin.y = 20;
        viewBounds.size.height = viewBounds.size.height - 20;
        self.webView.frame = viewBounds;
    }
    [super viewWillAppear:animated];
}
```

Unfortunately, when using the plugin and hiding the keyboard, this values are overridden, and my content is under the status bar again.

Is there a way to avoid this?

**Comment by mhweiner** [comment]
I had to remove the functionality to modify the behavior of the keyboard since iOS7.1 broke it anyway. I couldn't find a way to keep the hack in place (and it probably would have been unmaintainable). So, this shouldn't be an issue anymore.
