### ISSUE TITLE
Request to prevent scrolling

### ISSUE THREAD

**Issue by austinjackson** [mhweiner/CordovaiOSKeyboardPlugin#6]
If it isn't possible to resize the view (the main plugin can't do it either), would it be possible to prevent scrolling of the view when the keyboard is visible?  We could use your functions to get the height, then set a body height and appropriate classes to mimmic the view re-sizing.  This works, but the user can still scroll the view up revealing the gray background behind the keyboard.  I can prevent the touch move event from bubbling up, but not reliably.  Any way to do this from cordova?

**Comment by mhweiner** [comment]
I've already tried this. I haven't found a way to do it. I've gotten close, but there are always bugs/issues. Even worse, it won't be maintainable. I'm finally accepting that it's either not possible, or not worth it. Apple doesn't want you messing with it. You're better off using a native/hybrid approach for those screens.

**Comment by austinjackson** [comment]
I was able to prevent scrolling by editing Classes > Cleaver > CDVViewController.m (right around line 300) by adding scrollEnabled = NO. -webkit-overflow-scrolling: touch still works within the container.  Not sure if you can get the same hook in a plugin, but this change combined with your plugin and some javascript to change the body height on keyboard show/hide and rotate gives flawless results.

// prevent webView from bouncing
    // based on the DisallowOverscroll/UIWebViewBounce key in config.xml
    if (!bounceAllowed) {
        if ([self.webView respondsToSelector:@selector(scrollView)]) {
            ((UIScrollView_)[self.webView scrollView]).bounces = NO;
            ((UIScrollView_)[self.webView scrollView]).scrollEnabled = NO;
        } else {
            for (id subview in self.webView.subviews) {
                if ([[subview class] isSubclassOfClass:[UIScrollView class]]) {
                    ((UIScrollView_)subview).bounces = NO;
                    ((UIScrollView_)subview).scrollEnabled = NO;
                }
            }
        }
    }

**Comment by mhweiner** [comment]
Have you tried this with iOS7.1?

**Comment by austinjackson** [comment]
Yes.  Works.  Playing with it now.

The only issue remaining is if you focus an element positioned below where the keyboard will eventually be, the window scrolls up.  And, you can't scroll it back because scrolling is disabled.  The fix is to call a window.scrollTo(0, 0)  on keyboardDidShow.

**Comment by mhweiner** [comment]
I've had a host of issues ranging from long forms being unpredictable and
jumpy, to a black/white area showing up while the keyboard is animating up,
to glitchy animations, and everything in between. Are you telling me all of
these are fixed? Send me a pull request or link to your repo so I can try
it out!

**Comment by austinjackson** [comment]
I am personally not experiencing any of the issues you mention.  Unfortunately, I don't have any version control or Objective-C experience, but have been hacking together various results from StackOverflow and now have keyboard functionality your plugin used to provide.  In addition, toolbar hiding is working without any adverse affects.  I will explain what I did here so if someone with more experience wants to roll these changes into a plugin, then can.

### Install this plugin and the KeyboardToolbarRemover plugin, build your project and open in Xcode

https://github.com/don/KeyboardToolbarRemover

### Prevent scrolling by editing Classes > Cleaver > CDVViewController.m:

LINE 30 - add UIScrollViewDelegate

```
@interface CDVViewController () <UIScrollViewDelegate> {
    NSInteger _userAgentLockToken;
    CDVWebViewDelegate* _webViewDelegate;
}
```

LINE 195 - add scrollViewDidScroll method

```
// prevent scrolling entirely, since the view will scroll to selected elements
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    scrollView.contentOffset = CGPointZero;
}
```

LINE 300ish - disable scrolling and add delegate

```
    // prevent webView from bouncing
    // based on the DisallowOverscroll/UIWebViewBounce key in config.xml
    if (!bounceAllowed) {
        if ([self.webView respondsToSelector:@selector(scrollView)]) {
            ((UIScrollView*)[self.webView scrollView]).bounces = NO;
            ((UIScrollView*)[self.webView scrollView]).scrollEnabled = NO;
            ((UIScrollView*)[self.webView scrollView]).delegate = self;
        } else {
            for (id subview in self.webView.subviews) {
                if ([[subview class] isSubclassOfClass:[UIScrollView class]]) {
                    ((UIScrollView*)subview).bounces = NO;
                    ((UIScrollView*)subview).scrollEnabled = NO;
                    ((UIScrollView*)subview).delegate = self;
                }
            }
        }
    }
```

### Fix bug that occurs when hiding toolbar by editing Plugins > KeyboardToolbarRemover.m

Comment out lines 55-63

```
                if ([[peripheralView description] hasPrefix:@"<UIWebFormAccessory"]) {
                    // remove the extra scroll space for the form accessory bar
                  //  UIScrollView *webScroll;
                  //  if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 5.0) {
                  //      webScroll = [[self webView] scrollView];
                  //  } else {
                  //      webScroll = [[[self webView] subviews] lastObject];
                  //  }
                  //  CGRect newFrame = webScroll.frame;
                  //  newFrame.size.height += peripheralView.frame.size.height;
                  //  webScroll.frame = newFrame;

                    // remove the form accessory bar
                    [peripheralView removeFromSuperview];
                }

```

### The keyboard size method won't exclude the height of the accessory bar, so add 44px to any calculations you do (JQuery example):

```
bdy.on('keyboardDidShow', function(e) {
            bdy.css('height', wndw.height() - Keyboard.getHeight() + 44 + 'px');
        });
```

**Comment by mhweiner** [comment]
Wow, impressive hacking! I'll give it a try when I can. If it works, I can roll it into a separate plugin (since it is a bit hackish). The only thing I don't like is the fact that you're hard-coding 44px for the keyboard form accessory bar. Apple could change the height for this at any time, and it may even change depending on the language settings. Is there any way to use Obj-c to find the height of the bar? Also, of course I'm not happy with the use of private classes, but apparently people have been able to do this without getting rejected, or at least, so I've heard. That's why I'll keep it a seperate plugin just in case, so there is a choice available.

**Comment by austinjackson** [comment]
As far as I can tell, the problem with getting the height of the bar programmatically is that the toolbar can't be removed until the keyboard is created, which happens after the keyboardWillShow event, which is most likely where you want to use that value.  It is possible, however.  Take a look at line 222 in the file linked below from the cordova keyboard plugin.

https://github.com/apache/cordova-plugins/blob/master/keyboard/src/ios/CDVKeyboard.m

Looks like they are getting the bar height there with peripheralView.frame.size.height

Regarding private classes, I don't know the difference (but I know Apple does and may reject based on their use).  If the private classes in my solution above are from the keyboard remover, the linked CDVKeyboard appears to use slightly different classes to remove the keyboard.  If those are better, please note there is an issue (CB-6219) that is (apparently) fixed with the following patch:

https://github.com/apache/cordova-plugins/pull/6

**Comment by mhweiner** [comment]
Interesting. Anything that references that bar is using a private class.
Anything that references UIWebBrowserViewMinusAccessoryView is using a
private class. It seems this is fine, as long as you're not relying on
Apple approving it and have a backup plan in place, just in case.
